export const larraona = [
  {
    sector: "D1",
    image: "croquis_d1.webp",
    bloques: [
      {
        block: 1,
        name: "techo",
        grade: "6a",
        video: "https://www.instagram.com/piedras_medianas/reel/C8Ooug7tycB/",
        preview: "1.jpg",
      },
      {
        block: 2,
        name: "techo",
        grade: "6a+",
        video: "",
      },
      {
        block: 3,
        name: "techo",
        grade: "6c (comienza en 2 y sale hacia la derecha)",
        video: "",
      },
      {
        block: 4,
        name: "f2",
        grade: "?",
        video: "",
      },
      {
        block: 5,
        name: "paso de karli",
        grade: "7b",
        video: "",
      },
      {
        block: 6,
        name: "diedro",
        grade: "6c sit",
        video: "",
      },
      {
        block: 7,
        name: "",
        grade: "6b sit",
        video: "",
      },
      {
        block: 8,
        name: "techín",
        grade: "6b sit",
        video: "",
      },
      {
        block: 9,
        name: "",
        grade: "6b+ sit (empezar con filo y salir a la placa)",
        video: "",
      },
      {
        block: 10,
        name: "te voy a matar",
        grade: "6b+ sit",
        video: "",
      },
      {
        block: 11,
        name: "errores de juventud",
        grade: "6a, 6b+ sit",
        video: "",
      },
      {
        block: 11.5,
        name: "decrépitos pero contentos",
        grade: "7a sit (empieza en 11 y tira para la izquierda)",
        video: "",
      },
      {
        block: 12,
        name: "victimilla",
        grade: "6b+",
        video: "",
      },
      {
        block: 13,
        name: "liptonita",
        grade: "7b sit",
        video: "",
      },
      {
        block: 14,
        name: "arista panguelas",
        grade: "6c/7a sit",
        video: "",
      },
      {
        block: 15,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 16,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 17,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 18,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 19,
        name: "espolón del marqués de clase trabajadora",
        grade: "5c",
        video: "",
      },
      {
        block: 20,
        name: "lyme limón",
        grade: "5c",
        video: "",
      },
      {
        block: 21,
        name: "mocos de Roko",
        grade: "6a",
        video: "",
      },
      {
        block: 22,
        name: "los primeros blancos",
        grade: "6c, 6c+ sit",
        video: "",
      },
      {
        block: 23,
        name: "nunca llegarás a leyenda",
        grade: "6b, 6c sit",
        video: "",
      },
      {
        block: 24,
        name: "camisa hawaiana de fuerza",
        grade: "5a",
        video: "",
      },
      {
        block: 25,
        name: "miss expectativas",
        grade: "7b+ sit",
        video: "",
      },
      {
        block: 26,
        name: "es que soy zurdo",
        grade: "6a+ sit",
        video: "",
      },
      {
        block: 27,
        name: "el trono",
        grade: "6b sit",
        video: "",
      },
      {
        block: 28,
        name: "el tobogán",
        grade: "6c sit",
        video: "",
      },
      {
        block: 29,
        name: "rampa de lanzamiento",
        grade: "6b+ sit",
        video: "",
      },
      {
        block: 30,
        name: "txirrista",
        grade: "6b+ sit",
        video: "",
      },
      {
        block: 31,
        name: "las cuchillas",
        grade: "6c/7a (7c sit?)",
        video: "",
      },
      {
        block: 32,
        name: "trave",
        grade: "?",
        video: "",
      },
      {
        block: 33,
        name: "minimantle",
        grade: "?",
        video: "",
      },
      {
        block: 34,
        name: "proy",
        grade: "?",
        video: "",
      },
      {
        block: 35,
        name: "lance de las gafas",
        grade: "7a",
        video: "",
      },
      {
        block: 36,
        name: "makinistia",
        grade: "7b sit",
        video: "",
      },
      {
        block: 37,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 38,
        name: "fisura-trave",
        grade: "?",
        video: "",
      },
      {
        block: 39,
        name: "katalizer",
        grade: "4c sit",
        video: "",
      },
      {
        block: 39.5,
        name: "katacroken",
        grade: "6c sit",
        video: "",
      },
      {
        block: 40,
        name: "katapin",
        grade: "6a+ sit",
        video: "",
      },
      {
        block: 41,
        name: "kattalin",
        grade: "6c sit",
        video: "",
      },
      {
        block: 42,
        name: "katalina la grande",
        grade: "?",
        video: "",
      },
      {
        block: 43,
        name: "bodas de placa",
        grade: "?",
        video: "",
      },
      {
        block: 44,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 45,
        name: "calumnia vertebral",
        grade: "6c/7a sit",
        video: "",
      },
      {
        block: 46,
        name: "mutafukaz",
        grade: "7a sit",
        video: "",
      },
      {
        block: 47,
        name: "buenamierda",
        grade: "6a+",
        video: "",
      },
      {
        block: 48,
        name: "obra social",
        grade: "5c/6a",
        video: "",
      },
      {
        block: 49,
        name: "el digno",
        grade: "7a",
        video: "",
      },
      {
        block: 50,
        name: "plan abuelo",
        grade: "6a",
        video: "",
      },
      {
        block: 51,
        name: "el indigno",
        grade: "6b+ sit (morfo)",
        video: "",
      },
      {
        block: 52,
        name: "patologías previas",
        grade: "6c sit",
        video: "",
      },
      {
        block: 53,
        name: "",
        grade: "7a sit",
        video: "",
      },
      {
        block: 54,
        name: "",
        grade: "7a sit",
        video: "",
      },
      {
        block: 55,
        name: "",
        grade: "7a sit",
        video: "",
      },
      {
        block: 56,
        name: "",
        grade: "7a sit",
        video: "",
      },
      {
        block: 57,
        name: "la tetera",
        grade: "7b+ sit (acaba juntando manos en cantaco plano)",
        video: "",
      },
      {
        block: 58,
        name: "roco",
        grade: "mucho mucho canto",
        video: "",
      },
      {
        block: 59,
        name: "pachucho de amor",
        grade: "7a, 7b sit",
        video: "",
      },
      {
        block: 60,
        name: "uranio embrutecido",
        grade: "?",
        video: "",
      },
      {
        block: 61,
        name: "D1",
        grade: "7a",
        video: "",
      },
      {
        block: 61.5,
        name: "D1 direckt",
        grade: "7b+",
        video: "",
      },
      {
        block: 62,
        name: "trave D",
        grade: "6c hasta cazos",
        video: "",
      },
      {
        block: 63,
        name: "mattinharri",
        grade: "8a/b (?) sit",
        video: "",
      },
      {
        block: 64,
        name: "engendrillo",
        grade: "?",
        video: "",
      },
      {
        block: 65,
        name: "pony traumatizado",
        grade: "7b sit",
        video: "",
      },
      {
        block: 66,
        name: "sin blanca",
        grade: "7a+, 7b+? sit",
        video: "",
      },
      {
        block: 67,
        name: "mantle",
        grade: "6a+ sit",
        video: "",
      },
      {
        block: 68,
        name: "camilo sexto",
        grade: "5c, 6c sit",
        video: "",
      },
      {
        block: 69,
        name: "swing de azada",
        grade: "5a",
        video: "",
      },
      {
        block: 69.5,
        name: "sheldon",
        grade: "6c semi sit",
        video: "",
      },
      {
        block: 70,
        name: "jabalí street",
        grade: "6a",
        video: "",
      },
      {
        block: 71,
        name: "fibras lentas",
        grade: "5c",
        video: "",
      },
    ],
  },
  {
    sector: "El Vado",
    image: "croquis_el_vado.jpg",
    bloques: [
      {
        block: 1,
        name: "",
        grade: "6c/7a sit",
        video: "",
      },
      {
        block: 2,
        name: "",
        grade: "6c/7a sit",
        video: "",
      },
      {
        block: 3,
        name: "",
        grade: "6a+/6c+ sit",
        video: "",
      },
      {
        block: 4,
        name: "",
        grade: "4c",
        video: "",
      },
      {
        block: 5,
        name: "",
        grade: "6c sit",
        video: "",
      },
      {
        block: 6,
        name: "",
        grade: "6b sit",
        video: "",
      },
      {
        block: 7,
        name: "",
        grade: "6a sit",
        video: "",
      },
      {
        block: 8,
        name: "",
        grade: "5c",
        video: "",
      },
      {
        block: 9,
        name: "",
        grade: "6c/7b sit (sentado desde 10)",
        video: "",
      },
      {
        block: 10,
        name: "filo",
        grade: "?",
        video: "",
      },
      {
        block: 11,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 12,
        name: "",
        grade: "5c?",
        video: "",
      },
      {
        block: 13,
        name: "",
        grade: "7b sit",
        video: "",
      },
      {
        block: 14,
        name: "",
        grade: "6c sit (final directo)",
        video: "",
      },
      {
        block: 15,
        name: "",
        grade: "4/5?",
        video: "",
      },
      {
        block: 16,
        name: "pirata",
        grade: "6a sit",
        video: "",
      },
      {
        block: 17,
        name: "lula",
        grade: "6b sit",
        video: "",
      },
      {
        block: 18,
        name: "patas",
        grade: "6c sit",
        video: "",
      },
      {
        block: 19,
        name: "fistro rey",
        grade: "7b sit",
        video: "",
      },
      {
        block: 20,
        name: "la hoguera de las vanidades",
        grade: "7b/7c+ sit",
        video: "",
      },
      {
        block: 21,
        name: "la teniente muslowsky",
        grade: "6c sit",
        video: "",
      },
      {
        block: 22,
        name: "zapadores",
        grade: "?",
        video: "",
      },
      {
        block: 23,
        name: "reformas morales",
        grade: "7b+",
        video: "",
      },
      {
        block: 24,
        name: "arconada",
        grade: "6b",
        video: "",
      },
      {
        block: 25,
        name: "el vado",
        grade: "7a",
        video: "",
      },
      {
        block: 26,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 27,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 28,
        name: "sagastilepo",
        grade: "?",
        video: "",
      },
      {
        block: 29,
        name: "ataba",
        grade: "6b/c sit, ataba droite 7b sit",
        video: "",
      },
      {
        block: 30,
        name: "uci b",
        grade: "7a",
        video: "",
      },
      {
        block: 31,
        name: "la condición",
        grade: "?",
        video: "",
      },
      {
        block: 32,
        name: "la esquina",
        grade: "6c",
        video: "",
      },
    ],
  },
  {
    sector: "BATIBURRILLO",
    image: "croquis_batiburrillo.jpg",
    bloques: [
      {
        block: 1,
        name: "culto al puerco",
        grade: "sin hacer",
        video: "",
      },
      {
        block: 2,
        name: "daño total",
        grade: "7a sit",
        video: "",
      },
      {
        block: 3,
        name: "limpieza moral",
        grade: "sin hacer",
        video: "",
      },
      {
        block: 4,
        name: "velocidad absurda",
        grade: "6a-6a+ sit",
        video: "",
      },
      {
        block: 5,
        name: "el tiesto",
        grade: "sin hacer",
        video: "",
      },
      {
        block: 6,
        name: "fisura fácil",
        grade: "sin hacer",
        video: "",
      },
      {
        block: 7,
        name: "pilatos",
        grade: "sin hacer",
        video: "",
      },
      {
        block: 8,
        name: "plisti",
        grade: "4a",
        video: "",
      },
      {
        block: 9,
        name: "plasta",
        grade: "6b+",
        video: "",
      },
      {
        block: 10,
        name: "",
        grade: "sin hacer",
        video: "",
      },
      {
        block: 11,
        name: "el gran okoto",
        grade: "6a+-6b sit",
        video: "",
      },
      {
        block: 12,
        name: "el regalo de cumple",
        grade: "6c sit",
        video: "",
      },
      {
        block: 13,
        name: "el escaqueo",
        grade: "6a sit",
        video: "",
      },
      {
        block: 14,
        name: "",
        grade: "4",
        video: "",
      },
      {
        block: 15,
        name: "xolomogangstak",
        grade: "7a sit",
        video: "",
      },
      {
        block: 16,
        name: "",
        grade: "sin hacer",
        video: "",
      },
      {
        block: 17,
        name: "casa pukas",
        grade: "7a",
        video: "",
      },
      {
        block: 18,
        name: "",
        grade: "sin hacer",
        video: "",
      },
      {
        block: 19,
        name: "",
        grade: "sin hacer",
        video: "",
      },
      {
        block: 20,
        name: "las víctimas civiles",
        grade: "7b",
        video: "",
      },
      {
        block: 21,
        name: "",
        grade: "sin hacer?",
        video: "",
      },
      {
        block: 22,
        name: "",
        grade: "sin hacer?",
        video: "",
      },
      {
        block: 23,
        name: "",
        grade: "6a",
        video: "",
      },
      {
        block: 24,
        name: "vaginesil",
        grade: "sin hacer",
        video: "",
      },
      {
        block: 25,
        name: "el fraude",
        grade: "??",
        video: "",
      },
      {
        block: 26,
        name: "el segundo bloque más fácil de Larraona",
        grade: "",
        video: "",
      },
      {
        block: 27,
        name: "micraster",
        grade: "5c",
        video: "",
      },
      {
        block: 28,
        name: "",
        grade: "sin hacer",
        video: "",
      },
      {
        block: 29,
        name: "",
        grade: "6c+-7a+ sit",
        video: "",
      },
      {
        block: 30,
        name: "",
        grade: "6b+",
        video: "",
      },
      {
        block: 31,
        name: "",
        grade: "6a",
        video: "",
      },
      {
        block: 32,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 33,
        name: "ojito",
        grade: "6b-7a sit",
        video: "",
      },
      {
        block: 34,
        name: "",
        grade: "sin hacer",
        video: "",
      },
      {
        block: 35,
        name: "",
        grade: "sin hacer",
        video: "",
      },
      {
        block: 36,
        name: "kozkor",
        grade: "6b sit",
        video: "",
      },
      {
        block: 37,
        name: "geoda",
        grade: "6b",
        video: "",
      },
      {
        block: 38,
        name: "the zoquets",
        grade: "7a (primeras presas altas)",
        preview: "zoquets.jpg",
        video:
          "https://www.instagram.com/piedras_medianas/p/BuW7jP0nzsr/?img_index=1",
      },
      {
        block: 39,
        name: "fácil",
        grade: "",
        video: "",
      },
      {
        block: 40,
        name: "muy fácil",
        grade: "",
        video: "",
      },
      {
        block: 41,
        name: "la vira muy fácil",
        grade: "",
        video: "",
      },
      {
        block: 42,
        name: "fácil",
        grade: "",
        video: "",
      },
      {
        block: 43,
        name: "fácil",
        grade: "",
        video: "",
      },
      {
        block: 44,
        name: "fácil",
        grade: "",
        video: "",
      },
      {
        block: 45,
        name: "arista fácil",
        grade: "",
        video: "",
      },
      {
        block: 46,
        name: "latin kings",
        grade: "6b+ sit",
        video: "",
      },
      {
        block: 47,
        name: "drogradictos",
        grade: "6c sit",
        video: "",
      },
      {
        block: 48,
        name: "larratxakra izquierda",
        grade: "6b+-7b+ semi sit",
        video: "",
      },
      {
        block: 49,
        name: "larratxakra derecha",
        grade: "7a-7c sit",
        video: "",
      },
      {
        block: 50,
        name: "sobras políticas",
        grade: "6c",
        video: "",
      },
      {
        block: 51,
        name: "un poco alto",
        grade: "6a/b",
        video: "",
      },
      {
        block: 52,
        name: "elefante antiguo",
        grade: "6b+",
        video: "",
      },
      {
        block: 53,
        name: "fisura fácil",
        grade: "4c sit",
        video: "",
      },
      {
        block: 54,
        name: "",
        grade: "5b sit",
        video: "",
      },
      {
        block: 55,
        name: "infernu epela",
        grade: "6b+",
        video: "",
      },
      {
        block: 56,
        name: "por cada rayo que cae",
        grade: "7a",
        video: "",
      },
      {
        block: 57,
        name: "la sierra",
        grade: "6a",
        video: "",
      },
      {
        block: 58,
        name: "arista batiburrillo",
        grade: "7a",
        video: "",
      },
      {
        block: 59,
        name: "",
        grade: "sin hacer",
        video: "",
      },
      {
        block: 60,
        name: "",
        grade: "6b+ sit",
        video: "",
      },
      {
        block: 61,
        name: "arista michniak",
        grade: "7a sit",
        video: "",
      },
      {
        block: 62,
        name: "triángulo muymuymuy fácil",
        grade: "",
        video: "",
      },
      {
        block: 63,
        name: "",
        grade: "sin hacer",
        video: "",
      },
      {
        block: 64,
        name: "brutus",
        grade: "6b+",
        video: "",
      },
      {
        block: 65,
        name: "prótesis de cadera",
        grade: "7b",
        preview: "protesiscadera.jpg",
        video: "https://www.instagram.com/piedras_medianas/reel/BuYpdtcHYE8/",
      },
      {
        block: 66,
        name: "prótesis de polea",
        grade: "7a+-? sit",
        video: "",
      },
      {
        block: 67,
        name: "arista",
        grade: "6a+ sit",
        video: "",
      },
      {
        block: 68,
        name: "",
        grade: "sin hacer",
        video: "",
      },
      {
        block: 69,
        name: "",
        grade: "5c",
        video: "",
      },
      {
        block: 70,
        name: "gulote",
        grade: "6c",
        video: "",
      },
      {
        block: 71,
        name: "la muralla",
        grade: "sin hacer",
        video: "",
      },
      {
        block: 72,
        name: "langarra (derecha)",
        grade: "7a-7b/+ sit",
        video: "",
      },
      {
        block: 73,
        name: "langarra (izquierda)",
        grade: "sin hacer",
        video: "",
      },
      {
        block: 74,
        name: "",
        grade: "5a",
        video: "",
      },
      {
        block: 75,
        name: "oker",
        grade: "7a+",
        video: "",
      },
      {
        block: 76,
        name: "chilly Gonzales",
        grade: "6c-7a sit",
        video: "",
      },
      {
        block: 77,
        name: "puro y ligero",
        grade: "6c",
        video: "",
      },
      {
        block: 78,
        name: "mucho difícil",
        grade: "7a sit",
        video: "",
      },
      {
        block: 79,
        name: "rollo comando",
        grade: "6b+ sit",
        video: "",
      },
      {
        block: 80,
        name: "neopreno",
        grade: "6b+ sit",
        preview: "neopreno.jpg",
        video: "https://www.instagram.com/piedras_medianas/p/BuYVyR1nVl4/",
      },
    ],
  },
  {
    sector: "EL PUERTO",
    bloques: [
      {
        block: 1,
        name: "",
        grade: "? sentado, techo",
        video: "",
      },
      {
        block: 2,
        name: "atxoman",
        grade: "7c sentado",
        video: "",
      },
      {
        block: 3,
        name: "",
        grade: "",
        video: "",
      },
      {
        block: 4,
        name: "",
        grade: "6c sentado",
        video: "",
      },
      {
        block: 5,
        name: "",
        grade: "7a sentado, filo",
        video: "",
      },
      {
        block: 6,
        name: "",
        grade: "6b? sentado",
        video: "",
      },
      {
        block: 7,
        name: "",
        grade: "7a+ sentado, placa",
        video: "",
      },
      {
        block: 8,
        name: "",
        grade: "7b sentado",
        video: "",
      },
      {
        block: 9,
        name: "",
        grade: "",
        video: "",
      },
      {
        block: 10,
        name: "",
        grade: "",
        video: "",
      },
      {
        block: 11,
        name: "esto no es suiza",
        grade: "7c+ 8a+ sentado",
        video: "",
      },
      {
        block: 12,
        name: "ritmo canario",
        grade: "7c, lance hasta agujero",
        video: "",
      },
      {
        block: 13,
        name: "",
        grade: "p",
        video: "",
      },
      {
        block: 14,
        name: "",
        grade: "p",
        video: "",
      },
      {
        block: 15,
        name: "",
        grade: "6c sentado, filo",
        video: "",
      },
      {
        block: 16,
        name: "placa de las fresas",
        grade: "7a",
        video: "",
      },
      {
        block: 17,
        name: "",
        grade: "7a",
        video: "",
      },
      {
        block: 18,
        name: "",
        grade: "",
        video: "",
      },
      {
        block: 19,
        name: "",
        grade: "",
        video: "",
      },
      {
        block: 20,
        name: "",
        grade: "6c",
        video: "",
      },
      {
        block: 21,
        name: "",
        grade: "7a+",
        video: "",
      },
      {
        block: 22,
        name: "",
        grade: "6b+ sentado",
        video: "",
      },
      {
        block: 23,
        name: "",
        grade: "6b sentado",
        video: "",
      },
      {
        block: 24,
        name: "",
        grade: "7a sentado",
        video: "",
      },
      {
        block: 25,
        name: "",
        grade: "7a sentado, salir hacia derecha",
        video: "",
      },
      {
        block: 26,
        name: "",
        grade: "7b sentado como en 24 salir por izquierda",
        video: "",
      },
      {
        block: 27,
        name: "",
        grade: "",
        video: "",
      },
      {
        block: 28,
        name: "",
        grade: "",
        video: "",
      },
      {
        block: 29,
        name: "",
        grade: "",
        video: "",
      },
      {
        block: 30,
        name: "",
        grade: "",
        video: "",
      },
      {
        block: 31,
        name: "uno que llega",
        grade: "8a? sentado, 7a de pie",
        video: "",
      },
      {
        block: 32,
        name: "uno que no llega",
        grade: "7c+ sentado en 31, seguir recto, 7a de pie",
        video: "",
      },
      {
        block: 33,
        name: "",
        grade: "p",
        video: "",
      },
      {
        block: 34,
        name: "",
        grade: "",
        video: "",
      },
      {
        block: 35,
        name: "variant",
        grade: "8a sentado, 8b+ sorginetxe sentado más abajo",
        video: "",
      },
      {
        block: 36,
        name: "",
        grade: "",
        video: "",
      },
      {
        block: 37,
        name: "",
        grade: "7a morfo",
        video: "",
      },
      {
        block: 38,
        name: "",
        grade: "6b sentado",
        video: "",
      },
      {
        block: 39,
        name: "",
        grade: "",
        video: "",
      },
      {
        block: 40,
        name: "",
        grade: "",
        video: "",
      },
      {
        block: 41,
        name: "",
        grade: "",
        video: "",
      },
      {
        block: 42,
        name: "",
        grade: "6a expo!",
        video: "",
      },
      {
        block: 43,
        name: "",
        grade: "7b sentado, desplome",
        video: "",
      },
      {
        block: 44,
        name: "",
        grade: "7b placa alta",
        video: "",
      },
      {
        block: 45,
        name: "",
        grade: "7a sentado, desplome",
        video: "",
      },
      {
        block: 46,
        name: "",
        grade: "6c",
        video: "",
      },
      {
        block: 49,
        name: "",
        grade: "? empezar a la derecha, final en cazo a la izquierda",
        video: "",
      },
      {
        block: 50,
        name: "",
        grade: "7a+ comienzo a la izquierda, fin en cazo, 6c de pie",
        video: "",
      },
    ],
  },
  {
    sector: "EULATE",
    bloques: [
      {
        block: 1,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 2,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 3,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 4,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 4.5,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 5,
        name: "",
        grade: "6c+ sentado hacia izquierda",
        video: "",
      },
      {
        block: 6,
        name: "",
        grade: "? sentado en 5, seguir recto",
        video: "",
      },
      {
        block: 7,
        name: "",
        grade: "6c",
        video: "",
      },
      {
        block: 8,
        name: "murchante no es españa",
        grade: "7b+ sentado",
        video: "",
      },
      {
        block: 9,
        name: "",
        grade: "? sentado sin coger el filo",
        video: "",
      },
      {
        block: 10,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 11,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 12,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 13,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 14,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 15,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 16,
        name: "",
        grade: "7a+ sentado en canto gordo y seguir hacia derecha",
        video: "",
      },
      {
        block: 17,
        name: "",
        grade: "7c sentado en 16 y seguir recto",
        video: "",
      },
      {
        block: 18,
        name: "",
        grade: "6c+ sentado",
        video: "",
      },
      {
        block: 19,
        name: "",
        grade: "6b+ sentado",
        video: "",
      },
      {
        block: 20,
        name: "",
        grade: "7a sentado",
        video: "",
      },
      {
        block: 21,
        name: "",
        grade: "6c",
        video: "",
      },
      {
        block: 22,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 23,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 24,
        name: "",
        grade: "7a sentado",
        video: "",
      },
      {
        block: 25,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 26,
        name: "",
        grade: "6c+",
        video: "",
      },
      {
        block: 27,
        name: "",
        grade: "6b",
        video: "",
      },
    ],
  },
  {
    sector: "ALCANTARILLA-CALLEJON",
    bloques: [
      {
        block: 1,
        name: "el perro muchacho",
        grade: "6c sentado",
        video: "",
      },
      {
        block: 2,
        name: "",
        grade: "6b sentado",
        video: "",
      },
      {
        block: 3,
        name: "",
        grade: "6c sentado, salir a la izquierda por la roma",
        video: "",
      },
      {
        block: 4,
        name: "",
        grade: "6b",
        video: "",
      },
      {
        block: 5,
        name: "",
        grade: "7a placa, ñapas",
        video: "",
      },
      {
        block: 6,
        name: "",
        grade: "6c placa, monodedo y dinámico",
        video: "",
      },
      {
        block: 7,
        name: "",
        grade: "7a sentado",
        video: "",
      },
      {
        block: 8,
        name: "",
        grade: "7a+ final en canto aceptable",
        video: "",
      },
      {
        block: 9,
        name: "",
        grade: "7c desde invertidas, techo",
        video: "",
      },
      {
        block: 10,
        name: "la bacteria armónica",
        grade: "?",
        video: "",
      },
      {
        block: 11,
        name: "proyecto de markel",
        grade: "?",
        video: "",
      },
      {
        block: 12,
        name: "",
        grade: "7c+ sentado",
        video: "",
      },
      {
        block: 13,
        name: "el rey meón",
        grade: "7b",
        video: "",
      },
      {
        block: 14,
        name: "",
        grade: "7c sentado opcional grado similar",
        video: "",
      },
      {
        block: 15,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 16,
        name: "",
        grade: "7c+ sentado",
        video: "",
      },
      {
        block: 17,
        name: "",
        grade: "6a sentado",
        video: "",
      },
      {
        block: 18,
        name: "el número de oro",
        grade: "7a+",
        video: "",
      },
      {
        block: 19,
        name: "",
        grade: "7a desde nº18, 7b desde nº17",
        video: "",
      },
      {
        block: 20,
        name: "el deforestador",
        grade: "7a+ sentado, 7c sentado",
        video: "",
      },
      {
        block: 21,
        name: "",
        grade: "7a sentado en nº20, salir hacia la derecha",
        video: "",
      },
      {
        block: 22,
        name: "abiertas hasta el amanecer",
        grade: "7b+ dinámico",
        video: "",
      },
      {
        block: 23,
        name: "anicetobacter",
        grade: "? proyectaco, acabar en nº22",
        video: "",
      },
      {
        block: 24,
        name: "",
        grade: "7a morfo, 7b sentado",
        video: "",
      },
      {
        block: 25,
        name: "",
        grade: "6b+ sentado",
        video: "",
      },
      {
        block: 26,
        name: "herejía",
        grade: "7a+ sentado",
        video: "",
      },
      {
        block: 27,
        name: "",
        grade: "7b",
        video: "",
      },
      {
        block: 28,
        name: "",
        grade: "6c sentado",
        video: "",
      },
      {
        block: 29,
        name: "",
        grade: "7a sentado",
        video: "",
      },
      {
        block: 30,
        name: "",
        grade: "7a+ sentado salida hacia izquierda, salida directa",
        video: "",
      },
      {
        block: 31,
        name: "",
        grade: "4 sentado",
        video: "",
      },
      {
        block: 32,
        name: "",
        grade: "6c",
        video: "",
      },
      {
        block: 33,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 34,
        name: "berezi",
        grade: "8a+ sentado, 8b",
        video: "",
      },
      {
        block: 34.5,
        name: "",
        grade: "7a sentado",
        video: "",
      },
      {
        block: 35,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 36,
        name: "",
        grade: "6c sentado",
        video: "",
      },
      {
        block: 37,
        name: "neta que sí",
        grade: "8a+ sentado",
        video: "",
      },
      {
        block: 38,
        name: "",
        grade: "7b sentado",
        video: "",
      },
      {
        block: 39,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 40,
        name: "",
        grade: "6b",
        video: "",
      },
      {
        block: 41,
        name: "",
        grade: "7a",
        video: "",
      },
      {
        block: 42,
        name: "",
        grade: "7b",
        video: "",
      },
      {
        block: 43,
        name: "",
        grade: "6c",
        video: "",
      },
    ],
  },
  {
    sector: "CÁRCEL, SIBERIA",
    bloques: [
      {
        block: 1,
        name: "endika's move",
        grade: "?",
        video: "",
      },
      {
        block: 2,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 3,
        name: "",
        grade: "7a",
        video: "",
      },
      {
        block: 4,
        name: "",
        grade: "6b sentado",
        video: "",
      },
      {
        block: 5,
        name: "",
        grade: "6c sentado",
        video: "",
      },
      {
        block: 6,
        name: "",
        grade: "6a",
        video: "",
      },
      {
        block: 7,
        name: "perra chivata",
        grade: "7b+ comienzo en dos ñapas bajas",
        video: "",
      },
      {
        block: 8,
        name: "",
        grade: "6b+",
        video: "",
      },
      {
        block: 9,
        name: "",
        grade: "5a",
        video: "",
      },
      {
        block: 10,
        name: "",
        grade: "6c sentado hacia la derecha",
        video: "",
      },
      {
        block: 11,
        name: "",
        grade: "6b sentado",
        video: "",
      },
      {
        block: 12,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 13,
        name: "",
        grade: "7a sentado, monodedo",
        video: "",
      },
      {
        block: 14,
        name: "",
        grade: "7b+",
        video: "",
      },
      {
        block: 15,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 16,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 17,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 18,
        name: "",
        grade: "5a",
        video: "",
      },
      {
        block: 19,
        name: "",
        grade: "6a+; 6b+ sentado",
        video: "",
      },
      {
        block: 20,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 21,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 22,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 23,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 24,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 25,
        name: "",
        grade: "7b+ sentado",
        video: "",
      },
      {
        block: 26,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 27,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 28,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 29,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 30,
        name: "ortophonk",
        grade: "7b+ sentado",
        video: "",
      },
      {
        block: 31,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 32,
        name: "",
        grade: "7b sentado",
        video: "",
      },
      {
        block: 33,
        name: "el botxo",
        grade: "7b+ sentado",
        video: "",
      },
      {
        block: 34,
        name: "tiñoso",
        grade: "8a sentado",
        video: "",
      },
      {
        block: 35,
        name: "wichi the mosca",
        grade: "7b+ sentado",
        video: "",
      },
      {
        block: 36,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 37,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 38,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 39,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 40,
        name: "",
        grade: "7a sentado desde el fondo y salir recto",
        video: "",
      },
      {
        block: 41,
        name: "",
        grade: "6c sentado desde el fondo y salir hacia izquierda",
        video: "",
      },
      {
        block: 42,
        name: "",
        grade: "7b",
        video: "",
      },
      {
        block: 43,
        name: "",
        grade: "7b sentado",
        video: "",
      },
      {
        block: 44,
        name: "",
        grade: "?",
        video: "",
      },
      {
        block: 45,
        name: "",
        grade: "7c sentado",
        video: "",
      },
      {
        block: 46,
        name: "",
        grade: "7c+ sentado",
        video: "",
      },
      {
        block: 47,
        name: "",
        grade: "7a+",
        video: "",
      },
    ],
  },
  {
    sector: "OTROS",
    bloques: [
      {
        block: 1,
        name: "Lapili",
        grade: "6b sit",
        sector: "azpilduia",
        preview: "lapili.jpg",
        video: "https://www.instagram.com/piedras_medianas/p/BucSZF2nss7/",
      },
      {
        block: 2,
        name: "Os perdono hijosdeputa",
        grade: "6c",
        sector: "azpilduia",
        preview: "perdonohijosdeputa.jpg",
        video: "https://www.instagram.com/piedras_medianas/p/BucS4htnkxd/",
      },
      {
        block: 3,
        name: "Señor Cangrejo",
        grade: "7b",
        sector: "azpilduia",
        preview: "srcangrejo.jpg",
        video: "https://www.instagram.com/piedras_medianas/p/BucTTazHvfj/",
      },
      {
        block: 4,
        name: "Mister vinagres",
        grade: "6b",
        sector: "azpilduia",
        preview: "srcangrejo.jpg",
        video: "https://www.instagram.com/piedras_medianas/p/BucTTazHvfj/",
      },
      {
        block: 4,
        name: "Jirafa rey",
        grade: "6b sit",
        sector: "azpilduia",
        preview: "jirafarey.jpg",
        video: "https://www.instagram.com/piedras_medianas/p/BucT3zzHfa7/",
      },
      {
        block: 5,
        name: "Perro de presas",
        grade: "7c+ sit, 6c/7a de pie",
        sector: "viniendo de aranaratxe",
        preview: "perrodepresa.jpg",
        video: "https://www.instagram.com/piedras_medianas/p/BucVsAun3mP/",
      },
      {
        block: 6,
        name: "Grip-e",
        grade: "7b pie, 7c+ sit",
        sector: "",
        preview: "",
        video: "",
      },
      {
        block: 7,
        name: "Territorio hostil",
        grade: "proyecto",
        sector: "",
        preview: "",
        video: "",
      },
      {
        block: 8,
        name: "Agrofit",
        grade: "6c sit",
        sector: "aranaratxe",
        preview: "agrofit.jpg",
        video: "https://www.instagram.com/piedras_medianas/p/Bue-ZQgBBpo/",
      },
      {
        block: 9,
        name: "twerk",
        grade: "6a",
        sector: "aranaratxe",
        preview: "agrofit.jpg",
        video: "https://www.instagram.com/piedras_medianas/p/Bue-ZQgBBpo/",
      },
      {
        block: 10,
        name: "enturbiacequias",
        grade: "6b+, 7b sit",
        sector: "aranaratxe",
        preview: "agrofit.jpg",
        video: "https://www.instagram.com/piedras_medianas/p/Bue-ZQgBBpo/",
      },
      {
        block: 11,
        name: "Dónde están mis amigos?",
        grade: "6c de pie, 7a+ sit",
        sector: "aranaratxe",
        preview: "dondestanmisamigos.jpg",
        video:
          "https://www.instagram.com/piedras_medianas/p/BufA5CgBDIF/?img_index=1",
      },
    ],
  },
];
